[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules", "src/libraries"]
viaIr = true

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "params_first"
quote_style = "double"
number_underscore = "thousands"
override_spacing = true
wrap_comments = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
